apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: {TODO: CHANGE}
        imagePullPolicy: Always
        envFrom:
        - secretRef:
          name: payments-secrets
        - configMapRef:
            name: payments-config
        ports:
        - containerPort: 3004
      imagePullSecrets:
      - name: regcred
